### ISSUE TITLE
Can't install pod

### ISSUE THREAD

**Issue by Maxatma** [ReactiveKit/ReactiveAlamofire#2]
[!] Unable to satisfy the following requirements:

- `AlamofireReactive (~> 2.0.0-beta1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `AlamofireReactive (~> 2.0.0-beta1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by Maxatma** [comment]
Seems it just still doesn't work. Simple example of new way of api:
https://github.com/Maxatma/ReactiveAlamofire

**Comment by srdanrasic** [comment]
Thanks @Maxatma! I've just release non-beta v2 version that should work.

**Comment by Maxatma** [comment]
@srdanrasic Thanks you2  :) Will you fix other new classes? **DownloadRequest, UploadRequest and StreamRequest**.

**Comment by srdanrasic** [comment]
If you get some time to do a PR that would be great, otherwise I'll do it, but also not sure when I'll get some free time :)
